# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d69f5b930dc9504b7c99cf620572b59d5abb09060562e6ddca22fe0c6106c86397610c2611f327de58aa6947e630044d4b00a952ea9099f80e184f5ed573de22

test:
  secret_key_base: 0fd9b6c1e9d6af2e7052fcc0a438c90aaa36166181c0ba89e8f4d6bb36c5c64df847678c0073d9d93d81188dd2856655c8525f8b48723e6ec45a051488907ecf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
